name: CI

on:
  schedule:
    - cron:  '30 1 * * *'  
  push:

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: cache usr
      uses: actions/cache@v1
      env:
        cache-name: cache-usr-modules
      with:
        path: usr # npm cache files are stored in `~/.npm` on Linux/macOS
        key: usr-${{ env.cache-name }}
        restore-keys: |
          usr-${{ env.cache-name }}
    #- name: cache qt
    #  uses: actions/cache@v1
    #  env:
    #    cache-name: cache-qt-modules
    #  with:
    #    path: qt # npm cache files are stored in `~/.npm` on Linux/macOS
    #    key: qt-${{ env.cache-name }}
    #    restore-keys: |
    #      qt-${{ env.cache-name }}
    - name: Build
      run: |
        ls
        export QT_CI_LOGIN=${{ secrets.QT_CI_LOGIN }}
        export QT_CI_PASSWORD=${{ secrets.QT_CI_PASSWORD }}
        #if [ ! -d usr ]; then
        #  make all
        #  make ffmpeg
        #  make curl
        #  make libdash
        #else
        #  make libparc
        #  make hicn
        #  make libdash
        #fi
        #if [ ! -d qt ]; then
        #  make init_qt
        #  make qt_av
        #fi
