name: CI

on:
  schedule:
    - cron:  '30 1 * * *'  
  push:

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: cache usr
      uses: actions/cache@v1
      env:
        cache-name: cache-node-modules
      with:
        path: usr # npm cache files are stored in `~/.npm` on Linux/macOS
        key: usr-${{ env.cache-name }}
        restore-keys: |
          usr-${{ env.cache-name }}
    - name: cache qt
      uses: actions/cache@v1
      env:
        cache-name: cache-node-modules
      with:
        path: qt # npm cache files are stored in `~/.npm` on Linux/macOS
        key: qt_-${{ env.cache-name }}
        restore-keys: |
          qt_-${{ env.cache-name }}
    - name: Build
      run: |
        ls
        export QT_CI_LOGIN=${{ secrets.QT_CI_LOGIN }}
        export QT_CI_PASSWORD=${{ secrets.QT_CI_PASSWORD }}
        if [ ! -d usr ]; then
          make all
          make ffmpeg
          make curl
          make libdash
        else
          rm -rf usr/include/parc
          rm -rf usr/include/hicn
          rm -rf usr/include/libdash
          make libparc
          make hicn
          make libdash
        fi
        echo "aaa"
        ls -l qt/
        echo "bbb"
        if [ ! -d qt/Qt ]; then
          make init_qt
          make qtav
        fi
