name: CI

on:
  schedule:
    - cron:  '30 1 * * *'  
  push:

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Cache node modules
      uses: actions/cache@v1
      env:
        cache-name: cache-node-modules
      with:
        path: usr # npm cache files are stored in `~/.npm` on Linux/macOS
        key: usr-${{ env.cache-name }}
        restore-keys: |
          usr-${{ env.cache-name }}
    - name: Build
      run: |
        export QT_CI_LOGIN=${{ secrets.QT_CI_LOGIN }}
        export QT_CI_PASSWORD=${{ secrets.QT_CI_PASSWORD }}
        if [ ! -d usr ]; then
          make all
          make ffmpeg
          make curl
          make libdash
        else
          make libparc
          make hicn
          make libdash
        fi
        #make all_qt
