name: CI

on:
  schedule:
    - cron:  '30 1 * * *'  
  push:

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: cache usr
      uses: actions/cache@v1
      env:
        cache-name: cache-node-modules
      with:
        path: cace
        key: cache-${{ env.cache-name }}
        restore-keys: |
          cache-${{ env.cache-name }}
    - name: Build
      run: |
        ls
        export QT_CI_LOGIN=${{ secrets.QT_CI_LOGIN }}
        export QT_CI_PASSWORD=${{ secrets.QT_CI_PASSWORD }}
        if [ ! -d cache/usr ]; then
          make all_qt
          mv usr cache/usr
          mv qt cache/qt
        else
          ln -s cache/usr .
          rm -rf usr/include/parc
          rm -rf usr/include/hicn
          rm -rf usr/include/libdash
          make libparc
          make hicn
          make libdash
        fi
